// Junior-Tasks/Konzek-Junior-Task-Vue/src/components/list.vue
<template>
  <div class="list">
    <div class="list__group" list v-if="countries">
      <div
        class="list__group__box"
        v-for="(country, index) in countries"
        :key="index"
        @click="toggleSelection(index)"
        :style="{ backgroundColor: isSelected(index) ? randomColor() : '' }"
      >
        <h1 class="list__group__box__emoji">{{ country.emoji }}</h1>
        <h3 class="list__group__box__name">{{ country.name }}</h3>
        <p class="list__group__box__capital">{{ country.capital }}</p>
      </div>
    </div>
    <p v-else>Loading...</p>
  </div>
</template>

<script>
import { mapState } from "vuex";

export default {
  data() {
    return {};
  },
  computed: {
    ...mapState(["countries", "selectedCountries"]),
  },
  mounted() {
    if (this.countries) {
      this.automaticSelection();
    }
  },
  watch: {
    countries: {
      immediate: true,
      handler(newValue, oldValue) {
        if (newValue) {
          this.automaticSelection();
        }
        console.log("seçilmiş ülkeler", this.selectedCountries);
      },
    },
  },
  methods: {
    toggleSelection(index) {
      const selectedIndex = this.selectedCountries.indexOf(index);
      if (selectedIndex !== -1) {
        this.selectedCountries.splice(selectedIndex, 1);
      } else {
        this.selectedCountries.splice(0, this.selectedCountries.length);
        this.selectedCountries.push(index);
      }
    },
    isSelected(index) {
      return this.selectedCountries.includes(index);
    },
    randomColor() {
      return "#" + Math.floor(Math.random() * 16777215).toString(16);
    },
    automaticSelection() {
      this.selectedCountries.splice(0, this.selectedCountries.length);
      if (this.countries.length > 10) {
        this.selectedCountries.push(9);
      } else if (this.countries.length > 0) {
        this.selectedCountries.push(this.countries.length - 1);
      }
    },
  },
};
</script>

// Junior-Tasks/konzek-junior-task-react/src/components/list.js
import React, { useState, useEffect } from "react";
import { useSelector } from "react-redux";

const ListComponent = () => {
  const [selectedCountries, setSelectedCountries] = useState([]);
  const countries = useSelector((state) => state.Countries.countries);

  useEffect(() => {
    if (countries) {
      automaticSelection();
    }
  }, [countries]);

  const toggleSelection = (index) => {
    const selectedIndex = selectedCountries.indexOf(index);
    if (selectedIndex !== -1) {
      setSelectedCountries(selectedCountries.filter((i) => i !== index));
    } else {
      setSelectedCountries([index]);
    }
  };

  const isSelected = (index) => {
    return selectedCountries.includes(index);
  };

  const randomColor = () => {
    return "#" + Math.floor(Math.random() * 16777215).toString(16);
  };

  const automaticSelection = () => {
    setSelectedCountries([]);
    if (countries.length > 10) {
      setSelectedCountries([9]);
    } else if (countries.length > 0) {
      setSelectedCountries([countries.length - 1]);
    }
  };

  return (
    <div className="list">
      {countries ? (
        <div className="list__group">
          {countries.map((country, index) => (
            <div
              className="list__group__box"
              key={index}
              onClick={() => toggleSelection(index)}
              style={{
                backgroundColor: isSelected(index) ? randomColor() : "",
              }}
            >
              <h1 className="list__group__box__emoji">{country.emoji}</h1>
              <h3 className="list__group__box__name">{country.name}</h3>
              <p className="list__group__box__capital">{country.capital}</p>
            </div>
          ))}
        </div>
      ) : (
        <p>Loading...</p>
      )}
    </div>
  );
};

export default ListComponent;
